language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script: 
  - composer install -n
  - mysql -e 'create database SporTiu_test'
  - mv app/config/parameters.yml.dist app/config/parameters.yml

script: phpunit -c app
