imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

# Doctrine PROD Configuration
doctrine:
    dbal:
        driver:   "%database_driver_prod%"
        host:     "%database_host_prod%"
        port:     "%database_port_prod%"
        dbname:   "%database_name_prod%"
        user:     "%database_user_prod%"
        password: "%database_password_prod%"
        charset:  UTF8

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: sportiu
                        roles: 'ROLE_ADMIN'

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/install, roles: ROLE_ADMIN }
