imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine TEST Configuration
doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "127.0.0.1"
        port:     "8889"
        dbname:   "SporTiu_test"
        user:     "ecucurella"
        password: "eVmjudqm"
        charset:  UTF8
