imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine TEST Configuration
doctrine:
    dbal:
        driver:   "%database_driver_test%"
        host:     "%database_host_test%"
        port:     "%database_port_test%"
        dbname:   "%database_name_test%"
        user:     "%database_user_test%"
        password: "%database_password_test%"
        charset:  UTF8
