security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: eVmjudqm
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

        #login:
        #    pattern:  ^/login$
        #    security: false

        #secured_area:
        #    pattern:    ^/demo/secured/
        #    form_login:
        #        check_path: _security_check
        #        login_path: _demo_login
        #    logout:
        #        path:   _demo_logout
        #        target: _demo

    access_control:
        - { path: ^/leagues/, roles: ROLE_ADMIN }
