parameters:
#    ecucurella_assets.example.class: ecucurella\AssetsBundle\Example

services:
#    ecucurella_assets.example:
#        class: %ecucurella_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
