ecucurella_SporTiu_homepage:
    pattern:  /
    defaults: { _controller: ecucurellaSporTiuBundle:Clubs:index }
    
ecucurella_SporTiu_clubs:
    pattern:  /clubs
    defaults: { _controller: ecucurellaSporTiuBundle:Clubs:index }
    
ecucurella_SporTiu_clubs_id:
    pattern:  /clubs/club/{id}
    defaults: { _controller: ecucurellaSporTiuBundle:Clubs:club }
    
ecucurella_SporTiu_install:
    pattern:  /install
    defaults: { _controller: ecucurellaSporTiuBundle:Install:index }

ecucurella_SporTiu_install_schema:
    pattern:  /install/schema
    defaults: { _controller: ecucurellaSporTiuBundle:Install:createSchema }
    