parameters:
#    ecucurella_SporTiu.example.class: ecucurella\SporTiuBundle\Example

services:
#    ecucurella_SporTiu.example:
#        class: %ecucurella_SporTiu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
